"""added created column

Revision ID: a08b239470f3
Revises: 4a1822107283
Create Date: 2021-06-02 23:16:51.732737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08b239470f3'
down_revision = '4a1822107283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created')
    # ### end Alembic commands ###
